---
all:
  hosts:
    el-instance:
      ansible_host: 84.201.134.204
    k-instance:
      ansible_host: 84.201.131.160
    fb-instance:
      ansible_host: 84.252.128.131
  vars:
    ansible_connection: ssh
    ansible_user: centos
elasticsearch:
  hosts:
    el-instance:
kibana:
  hosts:
    k-instance:
filebeat:
  hosts:
    fb-instance:
