---
  - src: git@github.com:netology-code/mnt-homeworks-ansible.git
    scm: git
    version: "2.1.4"
    name: elastic
  - src: git@github.com:run0ut/kibana-role.git
    scm: git
    version: "0.0.2"
    name: kibana
  - src: git@github.com:run0ut/filebeat-role.git
    scm: git
    version: "1.0.0"
    name: filebeat
  - src: git@github.com:run0ut/logstash-role.git
    scm: git
    version: "1.0.2"
    name: logstash
